[package]
name = "blawg-client"
version = "0.1.0"
authors = ["Denver Smith <denverpsmith@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.2.18"
reqwest = "0.9.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.0.8"
hmac = "0.7.0"
sha2 = "0.8.0"
