[package]
name = "blawg"
version = "0.1.0"
authors = ["Denver Smith <denverpsmith@gmail.com>"]
edition = "2018"

[dependencies]
tempfile = "3.0.8"
chrono = "0.4"
reqwest = "0.9.18"
hmac = "0.7.0"
sha2 = "0.8.0"
structopt = "0.2.18"
serde = { version = "1.0", features = ["derive"] }
